@startuml
participant Client order 10
participant Server order 20

Client->Server : SYN
Server->Client : SYN + ACK
Client->Server : ACK

Server->Server : Generate random number
Client->Server : GUESS 50
Server->Client : LOWER
Client->Server : GUESS 25
Server->Client : HIGHER
Client->Server : GUESS 28
Server->Client : CORRECT
Client->Server : RESTART
Server->Client : ACK

== Guessing the number ==

Client->Server : QUIT
Server->Client : ACK + QUIT
Client->Server : ACK

@enduml