@startuml
participant Client order 10
participant Server order 20

Client->Server : CONNECT
Server->Client : ACK

Client->Server : BOUND 200
Server->Client : OK

Client->Server : GUESS 50
Server->Server : Generate random number
Server->Client : LOWER

Client->Server : GUESS 25
Server->Client : HIGHER

Client->Server : GUESS 28
Server->Client : CORRECT

Client->Server : RESTART
Server->Client : OK

== Guessing the number ==

Client->Server : QUIT
Server->Client : ACK

@enduml