@startuml
participant Client order 10
participant Server order 20

== Connection and set bound

Client->Server : GUESS 50
Server->Server : Generate random number
Server->Client : LOWER

Client->Server : RESTART
Server->Client : ERROR 1

Client->Server : GUESS 28
Server->Client : CORRECT

Client->Server : RESTART
Server->Client : OK

== Close connection ==
@enduml