@startuml
participant Client order 10
participant Server order 20

== Connection and set 100 as bound ==

Client->Server : GUESS 50
Server->Server : Generate random number
Server->Client : LOWER

Client->Server : GUESS a
Server->Client : ERROR 2

Client->Server : GUESS 521
Server->Client : ERROR 1

== End the game and close connection ==

@enduml