@startuml
participant Client order 10
participant Server order 20

== Connection ==

Client->Server : BOUND a
Server->Client : ERROR 1

Client->Server : BOUND -1
Server->Client : ERROR 2

Client->Server : GUESS 1
Server->Server : Generate a number
Server->Client : LOWER

Client->Server : BOUND 50
Server->Client : ERROR 3

== End the game and close connection ==
@enduml