@startuml
participant Client order 10
participant Server order 20
participant Emitter order 30

Emitter->Server : TEMP 1, 30
Client->Server : REQ_TEMP 1
Server->Client : TEMP 30

Client->Server : REQ_TEMP a
Server->Client : ERROR 1

Client->Server : REQ_TEMP 2
Server->Client : ERROR 2
@enduml